### PR TITLE
fix(example): remove default value for olb_private_ip

### PR DESCRIPTION
**Pull request by FoSix**
## Description

Fix examples: remove default value for `olb_private_ip` and move it to `example.tfvars`

## Motivation and Context

Value of this param depends on the client architecture so there is no default value for this param. It highly depends on the private subnet CDIR. Therefore hiding this value in the defaults makes it difficult to setup the example for a custom network ranges.

## How Has This Been Tested?

no test, one example was already setup like this. So this is only to align the rest.

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by damianfedeczko — APPROVED** [review]
Good catch 👍

**Review by migara — APPROVED** [review]
LGTM 👍🏽

**Comment by michalbil** [comment]
Great stuff. The only thing one can nit pick on is inconsistency in this section of PR's info:

```
Types of changes

    Bug fix (non-breaking change which fixes an issue)
    New feature (non-breaking change which adds functionality)
    Breaking change (fix or feature that would cause existing functionality to change)
```

It's either a breaking change or not. Depending on what will actually stay here, commit message may need to be updated accordingly.

**Comment by FoSix** [comment]
> Great stuff. The only thing one can nit pick on is inconsistency in this section of PR's info:
> 
> ```
> Types of changes
> 
>     Bug fix (non-breaking change which fixes an issue)
>     New feature (non-breaking change which adds functionality)
>     Breaking change (fix or feature that would cause existing functionality to change)
> ```
> 
> It's either a breaking change or not. Depending on what will actually stay here, commit message may need to be updated accordingly.

Fixed

**Pull request merged**
