### PR TITLE
feat: allow terraform versions 1.x

### PR DESCRIPTION
**Pull request by jabielecki**
## Description

Allow terraform versions 1.x.

Also autoformat all the code using terraform `fmt` v1.0. The `fmt` behavior is different (although compatible) between the old 0.12.31 version and the new 1.0.

### CODE REVIEW

**Review by devsecfranklin — COMMENTED** [review]
was any testing done on this?

**Comment by jabielecki** [comment]
@devsecfranklin Yes, it seems I forgot to mention it in the description. The main examples (transit_vnet_common and transit_vnet_dedicated) are able to apply and pass traffic on terraform-1.0.

**Review by damianfedeczko — APPROVED** [review]
Very nice update 👍

**Review by devsecfranklin — APPROVED** [review]
Good to see the formatting changes and some additional comments. 

Hard to figure out what was tested and what the results of that testing was.

**Comment by jabielecki** [comment]
Already merged as #110 closing this one.

**Pull request closed without merging**
