### PR TITLE
Feature: Add load balancer output

### PR DESCRIPTION
**Pull request by subaltra**
Output the load balancer object so the config is more customizable.  For example to set up extra back end pools so you can fail over active active firewalls for upgrades.

## Description

Added an entry in the outputs file to output the load balancer object

## Motivation and Context

This allows for customization, the ability to add more backend pools for manual grace full fail over

## How Has This Been Tested?

This is only an out put so shouldn't effect any other code. I cloned the repo and tested and it worked for me.

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [ x] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have added tests to cover my changes if appropriate.
- [ x] All new and existing tests passed.

### CODE REVIEW

**Review by damianfedeczko — CHANGES_REQUESTED** [review]
Hello @subaltra! Thanks for submitting your Pull Request - we will be happy to approve it once you resolve the small issue mentioned in the comment added to your PR - a missing bracket at the end of the output. 

Also, can you please  please update the module documentation using the `pre-commit` tool as described in the [CONTRIBUTING.md](https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/blob/develop/CONTRIBUTING.md#tools) in this PR? I closed the second PR you created for this sole purpose - #153. Thanks!

**Comment by FoSix** [comment]
Since the code was not fixed since May, I'd suggest to close this PR. It looks there's no interest around this change.

**Comment by pimielowski** [comment]
Hello @subaltra , thanks for this change!
Please follow the contribution page about pre-commit tool at https://github.com/PaloAltoNetworks/terraform-best-practices/blob/main/CONTRIBUTING.md#tools

**Review by pimielowski — CHANGES_REQUESTED** [review]
Please fix docs with pre-commit tools :)

**Comment by migara** [comment]
@subaltra I am going to close this PR, please let us know if you have a valid use case for this change

**Pull request closed without merging**
