### PR TITLE
docs (modules/vnet):  Fix variable description

### PR DESCRIPTION
**Pull request by Lostmaniac9**
## Description

Changed id in Variables.tf from `network_security_group_id` to `network_security_group`

## Motivation and Context

https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/issues/232

## How Has This Been Tested?

I ran the pre-commit tests to what I understand to be the standards of the Contributing document.

## Types of changes

Bug fix

## Checklist

- [ x ] I have updated the documentation accordingly.
- [ x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

I am slightly unsure if I ran the pre-commit script correctly since I don't entirely understand what it does, but I believe it ran correctly and didn't have any significant issues to report.

### CODE REVIEW

**Comment by FoSix** [comment]
@Lostmaniac9 - Thanks for opening this PR. Unfortunately we cannot merge it in this form, just two small steps to do before we can:

1. please take a look at the [Contributing.md](https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/blob/main/CONTRIBUTING.md#new-contributors:~:text=your%20local%20repository.-,Run%20the%20pre%2Dcommit%20script.,-See%20the%20tools) document and make sure you run `pre-commit` in order to update the REDME files
2. please follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) when titling the PR.

**Comment by Lostmaniac9** [comment]
I am a bit confused with how to proceed with this. I have been trying to run pre-commit to update the README files but it keep failing when trying to validate terraform docs and tflint and gives an exit code of 127. Any reading I have done in the Contributing.md document hasn't been able to help me.

What's more is that it looks like above my comment several checks were run for my commit that all worked out so now I am wondering if anything is wrong at all.

**Comment by migara** [comment]
@Lostmaniac9 can you please paste the error you're getting here?

**Comment by Lostmaniac9** [comment]
image
Hoping this image show up well because the formatting in the console isn't very good. I am pretty sure I've just installed terraform and tflint incorrectly but I haven't been able to figure out how.

**Comment by migara** [comment]
@Lostmaniac9 not sure entirely. Perhaps try to install `tflint` and `Terraform fmt` via a package manager like Chocolatey.

I will fix this for this PR

**Review by migara — APPROVED** [review]

**Pull request merged**
