### PR TITLE
DO NOT MERGE unify the format of variables documentation

### PR DESCRIPTION
**Pull request by FoSix**
This PR is here only to highlight differences when witching to the new variables documentation format as described in #257

### CODE REVIEW

**Comment by alperenkose** [comment]
I think the Reference section was better organized with the table format but I also think that it looks bad on pan.dev since it doesn't fit within the available width. And having the reference sections organized in the navigation pane in pan.dev is a nice thing to have. Considering both having the documentation formatted in markdown doc looks better to me.

**Comment by sebastianczech** [comment]
Great job 👍 
I like that approach to have 1 sentence for each variable in table and then details below.
I have 2 questions:
- what is the reason to treat `.header.md` as hidden file, not just `header.md` ?
- do we have possibility to add syntax colouring for examples embedded in variables description ?

**Comment by FoSix** [comment]
@sebastianczech 

> what is the reason to treat `.header.md` as hidden file, not just `header.md` ?

the header file is just a part of the Readme, not a *standalone* document. The dot and idea of *hiding* it is just to emphasise that fact

> do we have possibility to add syntax colouring for examples embedded in variables description ?

Sure, just add language specs in the variable description, like [here](https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/blob/a83b7c13bf42d63e3057cc48ac0d0d6729c0337f/modules/vnet/variables.tf#L70)
We didn't use that in the pass as table formatting didn't support that correctly. With document format the description is copied 1:1, hence all MD features should be supported

**Pull request closed without merging**
